### ISSUE TITLE
Implementation note / recommendation required for upload completion end point

### ISSUE THREAD

**Issue by LionelOnTech** [buildingSMART/documents-API#35]
When a large file is uploaded, it may take up to several minutes for upload completion call to finish stitching all parts together and complete the upload. Because of this, idle timeout may be triggered on many load balancers's default configuration. 

Examples for LB idle timeouts:
- [Oracle OCI LBaaS HTTP idle timeout of 60 seconds](https://docs.oracle.com/en-us/iaas/Content/Balance/Reference/connectionreuse.htm#IdleTimeoutSettings)
- [AWS ELB Connection idle timeout of 60 seconds](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout).

To ensure the upload completion does not timeout on large files, I suggest we add an implementation note / recommendation under [Upload Completion](https://github.com/buildingSMART/documents-API#33226-upload-completion) for servers to periodically send whitespace characters back to keep the connection from timing out. This is similar to what AWS does for [CompleteMultipartUpload](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html).

**Comment by ykulbak** [comment]
Closed by #36
