### ISSUE TITLE
Incosistency in visual

### ISSUE THREAD

**Issue by wcoeberghp4** [buildingSMART/documents-API#38]
Hello there,

Last week we ran into an issue while implementing the OpenCDE API that turned out to be caused by an inconsistency in the documentation. 

The chart shown in [3.2.1. Document Download Example](https://github.com/buildingSMART/documents-API?tab=readme-ov-file#321-document-download-example) of the Documents-API  mentions that after the user has selected documents in the UI, the local_callback_url should be called with a URL parameter called `selected_url`:

![image](https://github.com/buildingSMART/documents-API/assets/74407689/f9448bf9-71b2-4adf-8037-4d43f0532909)

However, the documentation itself states under [3.2.1.1.3. User Selects Documents in CDE UI](https://github.com/buildingSMART/documents-API?tab=readme-ov-file#32113-user-selects-documents-in-cde-ui) that it actually should be `selected_documents_url`:

![image](https://github.com/buildingSMART/documents-API/assets/74407689/3b2dbbc2-c7a2-4fe8-ad5c-81e1aa588d8f)

To avoid further issues, it would be nice if the chart would be updated.

_Edit: code format for selected_url_

Best regards

**Comment by GeorgDangl** [comment]
Fixed in 6482f5782644ce92148fe182276604a20041c483
