### ISSUE TITLE
State between download documents and upload documents

### ISSUE THREAD

**Issue by wcoeberghp4** [buildingSMART/documents-API#39]
Hi there,

We are running into an issue that we feel should not be happening. Our system supports aggregating documents from different folders (like search, or creating so-called smart folders that aggregate documents based on a property like file extension).

We think this is great, cause this means that users can open documents across folders in the client application and are not bound to their folder structure. However, that also means that documents with the same name can open simultaneously in the client application. And in the case of having documents with the same name (and if it can happen, you have to take it into account), the issue arises when a user then decides to upload the files. 

The only things we identified that are supported to distinguish files are:

for the file: file_name and some randomly generated session_file_id in the client application that does not relate to anything else, both useless in our case to map files to documents in our system

Then there is the option for the server_context, but in our case that also won't work as the state of the smart folder or search can change over the course of the user downloading document to the client application and starting to upload.

Are we missing something obvious in the OpenCDE documents protocol or is this not taken into account? Why doesn't the protocol prescribe using the document_id provided in the document download in the upload flow as well?

Regards

**Comment by GeorgDangl** [comment]
Hey @wcoeberghp4, thank you for raising this issue!

I'm not sure I fully understand your issue. When you download a document, you'll get a `document_id` (https://github.com/buildingSMART/documents-API/blob/main/swagger.yaml#L494), which can be used to identify the document. That will be unique per document, so you can use that to differentiate between files that have the same file name.

Later, when you do an upload, you have two options. You either manually let the user select a target location via the interactive flow, or you use the `document_id` to automatically create a new revision.

Can you maybe point me to the part in the flow diagram where the issue arises?

**Comment by wcoeberghp4** [comment]
Hi Georg,

Thanks for the swift reply. 

First off: we are looking at it from the perspective of the web application.

As far as we understand (and see happening in the application we are testing with), in 3.3.2 Upload flow, the document_id is used nowhere. [In the initial step](https://github.com/buildingSMART/documents-API#33221-initiating-upload), the payload is as follows: 

`POST /upload-documents
Body:
{
  "server_context": "7188a2be-6c4e-4e3b-b7e7-cd27f0d4ad67",
  "callback": {
    "url": "http://localhost:8080/cde-callback-example",
    "expires_in": 3600
  },
  "files": [
    {
      "file_name": "model.ifc",
      "session_file_id": "76ec9d91-0731-4405-b3c4-9bf945f9955b"
    }
  ]
}`

the files section inly provides the `file_name`, and the `session_file_id`, which is new at that point correct (at least stated by the documentation "The files array has a single element, and this file was assigned a client generated session_file_id, see" and what we see from the request of the client)? How would we get the document_id from there :)?

Regards

**Comment by wcoeberghp4** [comment]
I do now in the file that you sent me see that the document_id is supported in the files array: https://github.com/buildingSMART/documents-API/blob/6482f5782644ce92148fe182276604a20041c483/swagger.yaml#L633

**Comment by wcoeberghp4** [comment]
@GeorgDangl , however it is not required, we will check with our initial integration partner if they can add it

**Comment by wcoeberghp4** [comment]
https://github.com/buildingSMART/documents-API/issues/39#issuecomment-2064003833
