### ISSUE TITLE
Link Swagger Hub and update it

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/documents-API#4]
We're using the `swagger.yaml` file here in this repository to create the Swagger specification. We should host that directly in Swagger Hub.

@ykulbak knows how to do this😀

**Comment by GeorgDangl** [comment]
We should also consider if there's a way to automatically sync the `swagger.yaml` file from this repository to Swagger Hub whenever it is changed. The other way, from Swagger Hub to GitHub, seems to be working out of the box.

**Comment by GeorgDangl** [comment]
We could use this endpoint on Swagger Hub to automate it via GitHub Actions:
https://app.swaggerhub.com/apis-docs/swagger-hub/registry-api/1.0.63#/APIs/saveDefinition

**Comment by ykulbak** [comment]
@GeorgDangl @pasi-paasiala I've added an integration in swaggerhub which syncs the spec from swaggerhub to github. The sync is pushing to a branch called swaggerhub, please check it out. 

Sync from github to [swaggerhub](https://github.com/buildingSMART/documents-API/tree/swaggerhub) is only available with the Enterprise plan for swaggerhub.

**Comment by GeorgDangl** [comment]
See also #6 as an alternative.

I'm fine with either approach, let's discuss it together😀

**Comment by GeorgDangl** [comment]
Btw, the sync from Swagger Hub into the branch `swaggerhub` seems to overwrite the README at the moment. There's probably a checkmark somewhere, or we need to move the `swagger.yaml` to a sub folder.

**Comment by ykulbak** [comment]
@GeorgDangl I've edited the integration - the README is no longer overwritten, see the [swaggerhub-inbound](https://github.com/buildingSMART/documents-API/tree/swaggerhub-inbound) branch. I could also remove the hidden [.swagger-codegen-ignore](https://github.com/buildingSMART/documents-API/blob/swaggerhub-inbound/.swagger-codegen-ignore) file and the [.swagger-codegen](https://github.com/buildingSMART/documents-API/tree/swaggerhub-inbound/.swagger-codegen) directory; What do you think?

**Comment by GeorgDangl** [comment]
Yeah, I think we can remove the codegen directories as well - we haven't talked about it, but I don't see us creating and maintaining generated clients.
